name: Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Check for Lint Errors
        run: |
          if [[ $(git status --porcelain | grep '^.M') ]]; then
            echo "Linting failed. Please fix errors and try again."
            exit 1
          fi
